#!/usr/bin/env python3

"""
This script takes the really long file names generated by
by running the command

gimp -i -b '(process-cakes "*.xcf")' -b '(gimp-quit 0)'

i.e. running the batch file ~/.gimp-2.8/scripts/processcakes.scm
which ultimately depends on the naming scheme developed in
~/.gimp-2.8/plug-ins/process_NCS_xcf.py


and abbreviates them to something more manageable. the "translations" are stored
in the file "T-BN_fullnames.json"

for example

./T-BN5072928_fetalsurface_fixed_ruler_lights_filter_12_0910-dd.mask.png
./T-BN5072928_fetalsurface_fixed_ruler_lights_filter_12_0910-dd.png
./T-BN5072928_fetalsurface_fixed_ruler_lights_filter_12_0910-dd.raw.png
./T-BN5072928_fetalsurface_fixed_ruler_lights_filter_12_0910-dd.trace.png

are copied to

./shortfiles/T-BN5072928.mask.png
./shortfiles/T-BN5072928.png
./shortfiles/T-BN5072928.raw.png
./shortfiles/T-BN5072928.trace.png

and the line
{
 ...
 "T-BN5072928": "T-BN5072928_fetalsurface_fixed_ruler_lights_filter_12_0910-dd",
 ...
 }

 will appear in T-BN_fullnames.json

"""

import os
import os.path
import shutil
import json

abbreviations = dict()

# need this to save new files
try os.path.isdir('shortfiles')

for f in os.listdir():
    basename, ext = os.path.splitext(f)
    if ext != '.png':
        continue
    if basename.endswith('mask') or basename.endswith('trace') or basename.endswith('raw'):
        basename, subtype = os.path.splitext(basename)
    else:
        subtype = None
    newbase, _  = basename.split('_', maxsplit=1)
    if subtype is None:
        newname = ''.join((newbase,ext))
        abbreviations[newbase] = basename
    else:
        newname = ''.join((newbase,subtype,ext))
    shutil.copy2(f, os.path.join('shortfiles',newname))

with open('T-BN_fullnames.json','w') as w:
    json.dump(abbreviations, w, indent=1)


