# coding: utf-8
get_ipython().run_line_magic('clear', '')
get_ipython().run_line_magic('run', 'compare_parameters_alt.py')
get_ipython().run_line_magic('clear', '')
get_ipython().run_line_magic('run', 'compare_parameters_alt.py')
get_ipython().run_line_magic('clear', '')
get_ipython().run_line_magic('run', 'compare_parameters_alt.py')
get_ipython().run_line_magic('run', 'compare_parameters_alt.py')
import json
with open('compare_parameters_alt_quality_0.json', 'w') as f:
    json.dump(integral_scores, f, indent=True)
integral_scores
I = [i[1:] for i in integral_scores]
I
crvs = np.array(I)
crvs
_.shape
crvs.squeeze()
crvs
_.shape
crvs = crvs.squeeze()
crvs
_.shape
get_ipython().run_line_magic('who', '')
params
PARAMS
labels = [p['label'] for p in PARAMS]
labels
plt.boxplot(crvs)
fig = plt.figure()
fig, ax = plt.subplots()
fig, ax = plt.subplots()
fig, ax = plt.subplots()
ax.boxplot(crvs, labels=labels)
fig, ax = plt.subplots()
ax.boxplot(crvs, labels=labels)
ax.set_ylabel(orientation='horizontal')
fig, ax = plt.subplots(figsize=(20,20)))
ax.boxplot(crvs, labels=labels)
ax.set_ylabel(orientation='horizontal')
ax.set_title(f'$\Vmax$ dependence on Parametrization (25 samples)')
ax.set_xlabel('CRV')
ax.set_ylabel('Frangi parametrization type')
axl = plt.setp(ax, xticklabels=labels)
plt.setp(axl, rotation=45)
fig, ax = plt.subplots(figsize=(20,20))
ax.boxplot(crvs, labels=labels)
ax.set_ylabel(orientation='horizontal')
ax.set_title(f'$\Vmax$ dependence on Parametrization (25 samples)')
ax.set_xlabel('CRV')
ax.set_ylabel('Frangi parametrization type')
axl = plt.setp(ax, xticklabels=labels)
plt.setp(axl, rotation=45)
fig, ax = plt.subplots(figsize=(20,20))
ax.boxplot(crvs, labels=labels)
ax.set_title(f'$\Vmax$ dependence on Parametrization (25 samples)')
ax.set_xlabel('CRV')
ax.set_ylabel('Frangi parametrization type')
axl = plt.setp(ax, xticklabels=labels)
plt.setp(axl, rotation=45)
fig, ax = plt.subplots(figsize=(20,20))
ax.boxplot(crvs, labels=labels)
ax.set_title(r'$\Vmax$ dependence on Parametrization (25 samples)')
ax.set_xlabel('CRV')
ax.set_ylabel('Frangi parametrization type')
axl = plt.setp(ax, xticklabels=labels)
plt.setp(axl, rotation=45)
fig, ax = plt.subplots(figsize=(20,20))
ax.boxplot(crvs)
ax.set_title(r'$\Vmax$ dependence on Parametrization (25 samples)')
ax.set_xlabel('CRV')
ax.set_ylabel('Frangi parametrization type')
axl = plt.setp(ax, xticklabels=labels)
plt.setp(axl, rotation=45)
fig, ax = plt.subplots(figsize=(20,20))
ax.boxplot(crvs)
ax.set_title(r'$\V_{{\max}}$ dependence on Parametrization (25 samples)')
ax.set_xlabel('CRV')
ax.set_ylabel('Frangi parametrization type')
axl = plt.setp(ax, xticklabels=labels)
plt.setp(axl, rotation=45)
fig, ax = plt.subplots(figsize=(20,20))
ax.boxplot(crvs)
ax.set_title(r'$V_{\max}$ dependence on Parametrization (25 samples)')
ax.set_xlabel('CRV')
ax.set_ylabel('Frangi parametrization type')
axl = plt.setp(ax, xticklabels=labels)
plt.setp(axl, rotation=45)
fig, ax = plt.subplots(figsize=(12,6))
ax.boxplot(crvs)
ax.set_title(r'$V_{\max}$ dependence on parametrization (25 samples)')
ax.set_xlabel('Frangi parametrization type)
ax.set_ylabel('CRV')
axl = plt.setp(ax, xticklabels=labels)
plt.setp(axl, rotation=45)
fig, ax = plt.subplots(figsize=(12,6))
ax.boxplot(crvs)
ax.set_title(r'$V_{\max}$ dependence on parametrization (25 samples)')
ax.set_xlabel('Frangi parametrization type')
ax.set_ylabel('CRV')
axl = plt.setp(ax, xticklabels=labels)
plt.setp(axl, rotation=45)
